### ISSUE TITLE
Implement better logging output

### ISSUE THREAD

**Issue by cburgmer** [jasmine-contrib/grunt-jasmine-runner#6]
I've realized that grunt-jasmine-runner uses the plain output of the jasmine console runner.

I've written a TerminalReporter to add color and better structuring on the console and created a pull request with jasmine-reporters: https://github.com/cburgmer/jasmine-reporters/commit/9c2175c3e066161436e3e212ff673ae5dc44e602 - However the code would be a much better fit here.

There's quite probably a bit more work to put into to adapt it to the way grunt works, but it's still pretty close to the console runner, so the system is the same.

If I find some time I will look into adapting that code, but in the meantime there might be somebody to take over.

**Comment by jsoverson** [comment]
Thanks @cburgmer. I'm thinking about ways to make the jasmine API more generic so that the reporters don't need to communicate over the bridge and can be implemented better solely on the node/grunt side.

That might make your work easier if you wanted to contribute then. Maybe it would be possible to just bridge the jasmine reporter api directly through phantom but I don't know how many concessions will need to be made.

**Comment by jsoverson** [comment]
@cburgmer, this task is now being updated and maintained at [grunt-contrib-jasmine](https://github.com/gruntjs/grunt-contrib-jasmine)

That task makes it easier to add new logging output so if you are still interested, please check out that repo.
